### ISSUE TITLE
fit_repac function error

### ISSUE THREAD

**Issue by kendigsham** [eddieimada/REPAC#1]
First of all, thank you for creating this package.
I have tried your package with my own data (not downloaded from recount3 project), created a RangedSummarizedExperiment experiment from my BAM files and your 'mm10_pa' annotation. I used the 'summarizeOverlaps' function to do so.
I followed the steps in your quick start guide until I got the the function 'fit_repac', I got this error:
~~~~~
Error in `results[-c(6, 9, 10)]`:
! Can't negate columns past the end.
ℹ Locations 6, 9, and 10 don't exist.
ℹ There are only 0 columns.
~~~~~
this is from the last few lines of the code in your function. 
Does that mean I have no results ??
Also, is there a better way to generate counts from my own data so I can use our package??

Thank you so much

**Comment by eddieimada** [comment]
Hi kendigsham,

Have you tried using the function `rse_from_bam()`? It takes a vector of bam files, the annotation (mm10_pa), and a data frame with the samples metadata. You can then use the output with `fit_repac()`.

Let me know if this helps.

**Comment by kendigsham** [comment]
It worked. Thank you.
